#!/bin/bash

comm=$1

if [ $comm = "build" ]; then
  docker compose build --build-arg UID="$(id -u)" --build-arg GID="$(id -g)" --no-cache
elif [ $comm = "up" ]; then
  docker compose up -d
elif [ $comm = "stop" ]; then
  docker compose stop
elif [ $comm = "ps" ]; then
  docker compose ps
elif [ $comm = "psql" ]; then
  docker compose exec rdb psql
elif [ $comm = "redis" ]; then
  docker compose exec memory redis-cli
elif [ $comm = "next" ]; then
  docker compose exec next bash
elif [ $comm = "memory" ]; then
  docker compose exec memory bash
elif [ $comm = "rdb" ]; then
  docker compose exec rdb bash
else
  docker compose exec next npm run $comm
fi
