#!/bin/bash

comm=$1

if [ $comm = "psql" ]; then
  docker compose exec rdb psql
elif [ $comm = "redis" ]; then
  docker compose exec memory redis-cli
elif [ $comm = "next" ]; then
  docker compose exec next bash
elif [ $comm = "memory" ]; then
  docker compose exec memory bash
elif [ $comm = "rdb" ]; then
  docker compose exec rdb bash
else
  docker compose exec next npm run $comm
fi
