# name: Check
# 
# on:
#   pull_request:
#   push:
#     branches:
#       - main
# 
# jobs:
#   checks:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       # TODO use buildx
#       # - id: buildx
#       #   uses: docker/setup-buildx-action@v1
#       # - uses: actions/cache@v2
#       #   with:
#       #     path: /tmp/.buildx-cache-app # Buildxのキャッシュを指定
#       #     key: ${{ github.ref }}-${{ github.sha }} # キャッシュのキーを指定
#       #     restore-keys: |
#       #       ${{ github.ref }}
#       #       refs/head/main
#       # - uses: docker/build-push-action@v4
#       #   with:
#       #     push: false
#       #     builder: ${{ steps.buildx.outputs.name }} # Buildxでビルドすることを指定
#       #     tags: testapp-app-cached:latest # イメージ名を指定/docker-compose.ymlで参照する名前
#       #     load: true
#       #     context: .
#       #     file: ./docker/app/Dockerfile
#       #     cache-from: type=local,src=/tmp/.buildx-cache-app # キャッシュを指定
#       #     cache-to: type=local,dest=/tmp/.buildx-cache-new-app # キャッシュを指定
#       - run: |
#           ./build.sh
#           docker compose up -d
#           docker compose exec server npm install
#           docker compose exec front npm install
#       - run: ./dc server prettier_check
#       - run: ./dc server eslint_check
#       - run: ./dc server compile
#       - run: ./dc front prettier_check
#       - run: ./dc front lint
#       - run: ./dc front build
